baseURL = "http://ap4y.me/"
disableKinds = ["taxonomy", "taxonomyTerm", "RSS", "sitemap"]
languageCode = "en-us"
title = "~/home/ap4y"
pygmentsStyle = "github"
sectionPagesMenu = "main"

[[menu.main]]
identifier = "projects"
name = "Portfolio"
title = "Portfolio"
url = "/projects/"
weight = 1

[[menu.main]]
identifier = "code"
name = "Code"
title = "Code"
url = "/code/"
weight = 2

[[menu.main]]
identifier = "blog"
name = "Blog"
title = "Blog"
url = "/blog/"
weight = 3

[[menu.main]]
identifier = "about"
name = "About"
title = "About"
url = "/about/"
weight = 4

[permalinks]
blog = "/:year/:month/:day/:title/"
