on:
  push:
    branches: [ master ]

jobs:
  docker_build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: docker
      uses: docker/build-push-action@v1.1.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: ap4y/website
        tag_with_sha: true
        tag_with_ref: true
        dockerfile: Dockerfile
